# Dockerfile para el Frontend
FROM node:22.12.0 AS builder

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de configuración y dependencias
COPY frontend/package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de los archivos de la aplicación
COPY frontend .

RUN npm run build

FROM node:22.12.0 AS runner

WORKDIR /app

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/next.config.ts ./
COPY --from=builder /app/tailwind.config.ts ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules

ENV NODE_ENV=production

# Exponer el puerto que usará Vite
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["npm", "start"]