from .manga import Manga
from .manga_genres import manga_genres
from .manga_trend import MangaTrend
from .manga_characters import MangaCharacter
from .manga_trailer import MangaTrailer
from .external_link import MangaExternalLink
from ..shared.external_site import ExternalSite
from ..character.character import Character
from ..anime.anime_genres import anime_genres
from ..shared.external_site import ExternalSite
from ..shared.relations import Relations 